### ISSUE TITLE
Replace which by test builtin

### ISSUE THREAD

**Issue by Ypnose** [kristapsdz/oconfigure#12]
Hi there Kristaps,

I would like to ask you what do you think about replacing `which` by `test` builtin in `oconfigure` ? `test -x` is supported by almost all shells. I would say it's a major benefit. Testing an executable in all directories in `PATH` could be portable. I am thinking about something like this (I wrote this function for one of my project) :

```
chk_path() {
	# Return binaries ONLY. POSIX 'command' builtin returns functions.
	# local isn't specified by POSIX!
	local IFS
	local p

	IFS=':'
	for p in $PATH; do
		if [ ! -d "$p" ]; then
			continue
		fi
		if [ -x "${p}/${1}" ]; then
			printf "%s\n" "${p}/${1}"
			return 0
		fi
	done
}
```
What's your opinion about it ?

Cheers

**Comment by kristapsdz** [comment]
What problem are you trying to solve?  If `which` can't be found by `configure`, that's the least of your concerns! :)

**Comment by Ypnose** [comment]
On some popular distributions, `which` is not included on the build-tools metapackage. This tool is rarely needed elsewere. On our build farm at work, the clusters running do not include it and it seems to be fine. :)
Even if we can simply remove the required check, I thought it was a good idea to ask you.

**Comment by kristapsdz** [comment]
Looking for `which` style functions is quite the rabbit hole.  I'm convinced this should be fixed, and your snippet looks alright, but it seems find to just use `command -v`.  See the answer for https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then for reference.  What do your experiences tell you?  (All of my systems have `which`, so I'll rely on your findings.)

**Comment by Ypnose** [comment]
Thanks for your trust. I think you should stick with POSIX. In that case, `command -v` could do the trick. From my own experience, `command -v`also returns aliases and functions and sometimes, it creates unexpected results. To match binaries only if that's what you want, further tests would be required :

```
$ dash                                                                                       
$ echo $0
dash
$ command -v ls
/bin/ls
$ alias ls='ls -F'
$ command -v ls
alias ls='ls -F'
$ unalias ls
$ ls() { true; }
$ command -v ls
ls
```
As you can see, it needs filtering. aliases and functions are unfortunately quite common. The snippet I gave you is not perfect, but it tests executables directly from `PATH` directories (return codes have to be modified, tho).

`which` has many implementations. For example, I was wrong with Ubuntu. I installed the upcoming `20.04 LTS` beta with `debootstrap` (the system is very minimal) and a `which` shell script is included. It is from `debianutils` package. Let's see it:

https://salsa.debian.org/debian/debianutils/-/blob/master/which

It is not far from the previous snippet. I think we are walking on eggshells here, especially because I do not want to introduce any regression to `oconfigure`.

**Comment by kristapsdz** [comment]
This doesn't fix any problems I've seen, so I'm marking this as closed.  If you know of any real systems where `which` isn't provided, please re-open this and I'll look into it!
