### ISSUE TITLE
SHA2 docs are referring to MD5

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/oconfigure#17]
In the README.md, the text currently reads:
> Tests for the standalone sha2(3) functions, defining HAVE_**MD5** with the result.
>  If not found, provides a full complement of standalone (i.e., not needing any crypto libraries) **MD5** hashing functions.
> [… more MD5 function references …]
(emphasis mine)

It looks like this was just copy/pasted from the MD5 section but never updated. I'm not submitting a PR because I'm actually unsure about some of the nuances there with regards to C99 types etc.

Also see #15 for the libmd bit.

**Comment by kristapsdz** [comment]
Fixed, thanks!
