### ISSUE TITLE
CC/CFLAGS are misdefined when ./configure is run in a sub-make

### ISSUE THREAD

**Issue by paravoid** [kristapsdz/oconfigure#18]
This is perhaps easier to explain with a test case than with words: in a GNU+Linux system, add a `Makefile.test` in the root directory of oconfigure, with those contents:
```make
all:
	./configure
```

Then, run `make -f Makefile.test -w`.

`configure` has a couple of `make -sf` invocations, which are considered submakes by GNU Make, and thus `Entering directory` and `Leaving directory` messages are emitted by it. This makes the CC and CFLAGS outputs of `Makefile.configure` contain garbage, and in fact the file being syntactically invalid as well.

There is a relatively easy fix:
```diff
-CC=`printf "all:\\n\\t@echo \\\$(CC)\\n" | make -sf -`
-CFLAGS=`printf "all:\\n\\t@echo \\\$(CFLAGS)\\n" | make -sf -`
+CC=`printf "all:\\n\\t@echo \\\$(CC)\\n" | make --no-print-directory -sf -`
+CFLAGS=`printf "all:\\n\\t@echo \\\$(CFLAGS)\\n" | make --no-print-directory -sf -`
```
…but I doubt this would work under BSD Make. I don't have a BSD system to experiment on, but hoping you'd have a better idea on how to address this use case.

(The above test case is a simplified one, of a more complex sequence that happens when building Debian packages, so it's not just a theoretical problem)

**Comment by kristapsdz** [comment]
I've added a tentative fix to this by switching on the MAKELEVEL variable, which is set by GNU make when in a sub-make.  I'm marking this as fixed as it works on my Debian box: if it doesn't fit your needs, please re-open and let me know!
