### ISSUE TITLE
Support separate builds

### ISSUE THREAD

**Issue by bentley** [kristapsdz/oconfigure#2]
$ mkdir build && cd build
    $ ../configure && make

If all build output could optionally be confined to an arbitrary directory, blowing it away would leave me with a pristine source tree (very helpful in the ports tree where “make clean” doesn’t get passed through to the software’s makefile). This feature shows up in a lot of newer build systems like cmake and meson and I find myself using it quite a lot.

**Comment by kristapsdz** [comment]
I'm closing this just because oconfigure doesn't do anything with Makefiles.  So I'm not sure how this is something workable.  You can always do ../configure as all output is in the cwd anyway.
