### ISSUE TITLE
MANDIR on macOS

### ISSUE THREAD

**Issue by rnkn** [kristapsdz/oconfigure#22]
Hi, I'm not sure if this is a concern or not, but on macOS oconfigure sets `MANDIR` to `${PREFIX}/man` which is usually `/usr/local/man`. However, on macOS this directory is not in the default `MANPATH` with man pages usually installed to `/usr/local/share/man`.

It is of course very easy to call `# make MANDIR=/usr/local/share/man install` but I just thought I'd flag it for you :)

**Comment by la-ninpre** [comment]
i think it's already available. it can be specified with `./configure MANDIR=/usr/local/share/man` or through `configure.local` file. just write this there:

```
MANDIR=/usr/local/share/man
```

**Comment by rnkn** [comment]
@la-ninpre yep that's another way to specify it, but the point is more that `./configure` scripts are usually intended to generate a build tailored to the environment.

**Comment by kristapsdz** [comment]
This may be true, but the environment is diverse enough that this is impractical to implement except as something the operator can override.  For example, you say Mac OSX, but in hombrew, the installation path would be */usr/local/Cellar/progname/share/man*.  In MacPorts, it's */opt/local/man*.  So assuming **PREFIX**, we're still looking at share vs no-share.

Then Linux has */usr/share/man* according to the FHS, but then further */usr/local/man*!?  And then there's Nix and the endless other johnny-come-lately package managers scattering manpages where they want.

So Paul, I see what you're getting it, and agree to a certain extent, but think this is easier left alone.

The only thing I can think of that might be useful is to have `./configure` print out the paths it's setting for *Makefile.configure* as a reminder to the package maintainer where they're going.  If there's anything you can think of beyond hard-coding checks in `./configure` for MacPorts, HomeBrew, Linux, etc., then let me know!

**Comment by rnkn** [comment]
Good points! I wasn't sure whether tailoring to MacOS was a project goal. Given the diaspora of man paths, I think you're right that it should not be :)
