### ISSUE TITLE
glibcs sys/queue.h might be insufficient

### ISSUE THREAD

**Issue by Duncaen** [kristapsdz/oconfigure#5]
I just noticed it now, glibcs version is missing all the `*_FOREACH_SAFE` macros.

**Comment by kristapsdz** [comment]
I don't follow...?  Our compat has the FOREACH_SAFE functions.  Is there something I should or shouldn't be doing?

**Comment by Duncaen** [comment]
I think it would be good to test for availability of `FOREACH_SAFE` in `test-sys_queue.c` or is this something that should be done per project, if the `FOREACH_SAFE` macros are needed?

**Comment by kristapsdz** [comment]
Haha!  This just bit in me a new project that uses TAILQ_FOREACH_SAFE.  I'm now modifying the test to specifically look for that function.

**Comment by kristapsdz** [comment]
Thank you!
