### ISSUE TITLE
get/setprogname issues

### ISSUE THREAD

**Issue by The-King-of-Toasters** [kristapsdz/oconfigure#8]
Currently, the presence of `getprogname()`, `program_invocation_short_name` and `__progname` are checked before erroring at the pre-processor level. This means we can't compile on systems that don't have any of these (e.g. Solaris 10, yeah I know) where it would be better to work around it.

Another annoyance is that, on systems where getprogname fails but the others succeed, `HAVE_GETPROGNAME` is not true, leading to checks like this:

```c
#if !(HAVE_GETPROGNAME || HAVE_PROGRAM_INVOCATION_SHORT_NAME || HAVE__PROGNAME)
	const char *progname;
	if ((progname = strrchr(argv[0], '/')) == NULL)
		progname = argv[0];
	else
		progname++;
	setprogname(progname);
#endif

```

This is from me patching out the cpp error I mentioned above. I think it would be better to provide an implementation of getprogname if all else fails. Currently, mandoc has the folllowing (compat_progname.c):

```c
#include "config.h"

#if HAVE_PROGNAME
int dummy;
#else
static const char *progname;

void
setprogname(const char *name)
{

	progname = name;
}

const char *
getprogname(void)
{

	return progname;
}

#endif
```

Where main would set progname as so:

```c
#if HAVE_PROGNAME
	progname = getprogname();
#else
	if ((progname = strrchr(argv[0], '/')) == NULL)
		progname = argv[0];
	else
		++progname;
	setprogname(progname);
#endif
```

**Comment by kristapsdz** [comment]
What about getexecname()? Is that a Solaris 10 function?  If so, it's trivial to write a test and add it to the chain ifdef in the compat, and not have the porter worry about it at all.

**Comment by The-King-of-Toasters** [comment]
Sounds good, I'll make a pull request for that. ~~Unfortunately I lost access to a Solaris 10 server, so I won't be able to test it.~~ ~~Nevermind, I got access to it again.~~ Ha, scratch that again. Apparently my uni switched it to a Linux Mint server of all things. I'll try my luck with illumos instead.
